### ISSUE TITLE
vcf writer issue

### ISSUE THREAD

**Issue by sridhar0605** [hanfang/Topsorter#11]
error 1:
python topsorter.py -i large_svs.vcf 
[status]	Topsorter started at 2017-05-15 17:29:19.555427
[status]	Reading the vcf file: large_svs.vcf
Traceback (most recent call last):
  File "topsorter.py", line 491, in <module>
    worker.readVcf()
  File "topsorter.py", line 81, in readVcf
    with open(fn, 'r') as f:
IOError: [Errno 2] No such file or directory: '/seq/schatz/hfang/Develop/Topsorter/data/grch38.chrom.sizes.txt'

#fixed gave current path

error2: 
python topsorter.py -i large_svs.vcf 
[status]	Topsorter started at 2017-05-15 17:36:36.966442
[status]	Reading the vcf file: large_svs.vcf
[execute]	Exporting the large SVs to vcf and flanking regions to a bed file
Traceback (most recent call last):
  File "topsorter.py", line 494, in <module>
    worker.exportVcfBed()
  File "topsorter.py", line 107, in exportVcfBed
    vcf_writer.write_record(record)
UnboundLocalError: local variable 'vcf_writer' referenced before assignment

**Comment by hanfang** [comment]
Hi there,

Thanks for this. I should have some bandwidth to look into this in ~3 weeks. Thanks.

Han

**Comment by sridhar0605** [comment]
Hello team, 

Did you get some time to look at this?

Thanks,
