### ISSUE TITLE
Topsorter for misassemblies

### ISSUE THREAD

**Issue by dcopetti** [hanfang/Topsorter#12]
hello,
I am wondering if I could use Topsorter to detect misassemblies in my scaffold-level diploid assembly (produced from PE, MP and 10x data by NRGene), in particular with the caveat that I would be using the same 10x data that built the scaffolds.
If it won't work, do you have any idea of what I could use?
Thanks,
Dario

**Comment by fritzsedlazeck** [comment]
Hi Dario,
I am sorry but this project is not ready yet and needs some further development and testing. 

You can check out Assemblytics or other methods for quality assessment of your scaffolds. However, it gets very tricky since you have a diploid genome. 
I hope that helps
Fritz
