### ISSUE TITLE
Update barcode_profile.py

### ISSUE THREAD

**Issue by hanfang** [hanfang/Topsorter#8]
Hi @srividya22, 

Since we are merging the codes, can you implement the following for [barcode_profile.py](https://github.com/hanfang/Topsorter/blob/master/scripts/barcode_profiles.py)? Thanks.

1. Can you convert the script in to a class, so that I can import the class from another function? 
2. Can you make it into python2-3 compatible? Like [here](http://python-future.org/compatible_idioms.html)
3. Styling request: Can you follow the [PEP8 styles guide](https://www.python.org/dev/peps/pep-0008/)? In particular, can you use four spaces instead of two? Currently there are mixed tabs and spaces in the script.

**Comment by hanfang** [comment]
TO-DO: Speed up the process.

**Comment by srividya22** [comment]
Done
